### ISSUE TITLE
use generated context from interpretation model

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clinvar-submitter#1]
Generated context is available at http://datamodel.clinicalgenome.org/interpretation/json/context

Will also need to make sure this context works appropriately with VCI->clingen transformation ( @cbizon )

**Comment by larrybabb** [comment]
obsolete. the generated context is currently at dataexchange.clinicalgenome.org/interpretation/json/context.  This is being used by the VCI->clingen transformation.
