### ISSUE TITLE
Verify coordinate math

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clinvar-submitter#2]
The 0-based to 1-based transformations in `form.clj` (specifically `variant-stop`) add 1 to both the start and stop coordinates. Typically, 0-based "interbase" coordinates are half-open (exclusive on the left, inclusive on the right) and 1-based coordinates are closed/inclusive.

So, I'm pretty sure that only the start needs to be incremented to go from our allele region representation to that expected by clinvar.

**Comment by larrybabb** [comment]
@bpow the end needs to be incremented when it is an Insertion "only" (not an indel).  you can see this plainly from our [Coordinate Numbering Examples](http://datamodel.clinicalgenome.org/clingen-static-resources/images/variant_numbering_examples.png) (see Row 7 for example).  The last set of 0-based coordinates show the representation that the allele registry data uses.  And we are trying to produce the middle "Variant Format" set.

So anything other than "Ins" add 1 to the start and nothing to the end.  For Ins, add nothing to the start and 1 to the end.  (Indels work like substitutions or dels.)

Please close if this is correct.

**Comment by bpow** [comment]
Got it, I hadn't adequately parsed the clojure expression:

```lisp
(if (and (str/blank? ref) (not (str/blank? alt))) (+ 1 (get stop "index")) (get stop "index"))))
```
to recognize that it is an `if` to only add 1 to stop in cases of insertions, to account for (this bit of) HGVS weirdness.
