### ISSUE TITLE
VCI classifications with MOI adjective selections cause issues with ClinVar submissions

### ISSUE THREAD

**Issue by sambaxter** [clingen-data-model/clinvar-submitter#24]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/19212392/166820059-bbfde8be-7ca6-4fe1-91f7-3f6e37fb41eb.png">

If a user selects X-linked as the inheritance and add an adjective (ex. dominant) in the VCI the value that is exported in the ClinVar submission data is not compatible with the ClinVar submission data model.  Can the adjective be removed from the export so that the final value is just "x-linked inheritance"?

**Comment by larrybabb** [comment]
![image](https://user-images.githubusercontent.com/959003/166944980-5e6f1000-1da9-4382-bafa-bfb0602021a2.png)
