### ISSUE TITLE
ClinVar Submitter service returning 500 error

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/clinvar-submitter#36]
Here's the data being submitted from the VCI:
[submitter-source.txt](https://github.com/clingen-data-model/clinvar-submitter/files/9013665/dfc8-submitter-source.txt)

and here's the response:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v1/submission. Reason:
<pre>    Response map is nil</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```
This may or may not be relevant, but within the VCI, the source interpretation does not have an MOI (mode of inheritance).

**Comment by larrybabb** [comment]
To close this I need to run an integrated test with a VCI instance that allows me to verify the new feature is working before we can deploy the updates to production. 
Currently we are waiting on Stanford to provide a VCI instance that points to the staging instance of the clinvar-submitter service.
