### ISSUE TITLE
Modify VCI-ClinVar submission process to include annotation of updates vs novel

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-submitter#4]
ClinGen SP ticket #[CSP-145](https://broadinstitute.atlassian.net/browse/CSP-145)

The larger request that this supports is the need by stakeholders to be able to more easily submit approved and published VCI classifications to ClinVar. To date we have created a service called ClinVar-Submitter, which runs on the Broad's GCP and is used solely by the VCI application. The ClinVar-Submitter service was originally designed and built as a command line service and was supported and tested to accept one or more variant classification records (in sepio json format) along with a mapping file that had a historical mapping of previous VCI classification record keys (aka local-keys) to the SCV accession ids in ClinVar. These two files are the primary sources that enable the service to generate the TSV file that aligns directly with the ClinVar Submission Excel form provided by NCBI. 

When we converted the CLI version of the clinvar-submitter application to a REST service we dropped the ability to send in an historical mapping of VCI local-keys to SCV accessions and the VCI team designed to use the service by allowing one Classification at a time to be sent to the clinvar-submitter service. While this still proves to be much more useful than nothing (which forces the VCI users to manually collect and build the ClinVar submission records) it did drop the important aspect of being able to determine whether a given submission record was a "new" or Novel submission versus an "update".  Since most submissions are new it works most of the time, but we are entering a time now that more and more updates to previously submitted VCI classifications are occurring. Currently, the VCEPs or VCI users must manually edit the generated Clinvar TSV records to place the SCV id and the term "update" at the end of each clinvar submission record in the excel submission form. This is creating a pain point as mistakes are being made and time is being wasted .

To solve this we would like to automatically maintain a VCI local-key to SCV accession id mapping file in a GCP bucket so that the clinvar-submitter service can cache it and use it to do the look up that is already built into the service. So this request focuses on fulfilling that by finding the minimal viable solution to create and update that mapping file and tweak the clinvar-submitter service to make that happen.

Ultimately we may want to refactor this to get the SCV ids from a GraphQL query in the future, unless this MVP solution proves to be minor in terms of technical debt.

**Comment by dazzariti** [comment]
With Stanford for review
